server:
  port: 8050
spring:
  application:
    name: Zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    news-serviceId:
      path: /news-server/**   # 所有访问/news/**的请求都会转发使用到NewsServer
      service-id: NewsServer   #eurka中的服务名
    tag-serviceId:
      path: /tag-server/**   # 所有访问/news/**的请求都会转发使用到NewsServer
      service-id: TagServer   #eurka中的服务名
    comment-serviceId:
      path: /comment-server/**
      service-id: CommentServer
    search-serviceId:
      path: /search-server/**
      service-id: SearchServer
    user-serviceId:
      path: /user-server/**
      service-id: UserServer